# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec97cf550d9881ad4a23fc64b58a77191960773416417ef7388a1ca067f00ee00f539e3cd9e7bf9187947af2463c7c710c2369d6845aae949de38c6b512bf8a4

test:
  secret_key_base: 85d616f69bcb198fdf955f5bcbafd3ceca6b0f81e741cbf03e491da239c928dcd4b7b39689e58504dd4e525bd7f2ac45baca75139375957e1891897247ae3f9f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
